### PR TITLE
add german example sentences

### PR DESCRIPTION
**Pull request by maxbachmann**

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Icanhazdadjokes.com has german jokes too now? The module is set as EN only, but that can change

**Comment by maxbachmann** [comment]
Oh I did not check that o.0
just did translations without thinking about it ...
guess I will have to look out for a german joke api

**Comment by Psychokiller1888** [comment]
:)

This one has german support: https://github.com/project-alice-powered-by-snips/ProjectAliceModules/tree/master/PublishedModules/Psychokiller1888/RandomUselessFacts

**Comment by maxbachmann** [comment]
Ok I will add translations for it

**Pull request closed without merging**
