### PR TITLE
reduce complexity of onMessage

### PR DESCRIPTION
**Pull request by maxbachmann**
@glueckself 
each intent has a own function now assigned in self._ACTIONS, since the complexity of onMessage would otherwise get quite big when more intents get added.
Not sure whether this makes sence depending on what how the other functions look, so I leave it here as a idea for further development

### CODE REVIEW

**Comment by glueckself** [comment]
I think that's a good idea. Play/stop/next/prev are simple methods, but when it gets to playlist management or interaction with other modules the methods are going to get complex.
I guess I would've refactored onMessage at some point, but we might as well start now.

Thank you :)

One question though: you're using the _ACTIONS dict in onMessage() to call the specific method, but you're also passing it to the the parent class (Module). Would it make sense to have Module implement onMessage() and that calls the method in _ACTIONS? And for special cases, the module can replace onMessage() with it's own (and it then has to filter etc).

**Comment by maxbachmann** [comment]
I actually thought about this aswell while refactoring. I guess it might make sence to include this in alpha3 (or maybe even alpha2) when @Psychokiller1888 likes this idea aswell

The filtering at the top is already done by alice starting alpha2 ;)

**Comment by maxbachmann** [comment]
edit: just implemented it let's see what @Psychokiller1888 thinks about it ;)

**Comment by Psychokiller1888** [comment]
So no more onMessage for modules, but every intent calling their own method within the modules? I like it, gotta think further what it could involve, but I'm for it. Would greatly improve AliceCore readability

**Comment by maxbachmann** [comment]
well they still have the possibility to use onMessage when they want to have a different behaviour

**Comment by Psychokiller1888** [comment]
Can be included in alpha2 if the modules don't need rewrite for it :)

**Comment by maxbachmann** [comment]
it still has the same behaviour in my PR. The behaviour only changes when the actionMap is passed in the init

**Comment by Psychokiller1888** [comment]
So we do the big change for alpha 3 then. I'm finishing a logic cleanup related to the same kwargs problem and the flow from downloading, installing, updating etc etc

**Comment by maxbachmann** [comment]
@glueckself updated here to show how it can be done in alpha2 now. In this case I think it makes sence to overwrite the onMessage method because otherwise the not connected case has to be implemented for each intent

**Comment by Psychokiller1888** [comment]
If there's one thing I would rewrite: ACTIONS => INTENTS

**Comment by Psychokiller1888** [comment]
And fusion supportedIntent with the new handling

**Comment by Psychokiller1888** [comment]
@maxbachmann Something like this? https://github.com/project-alice-powered-by-snips/ProjectAlice/pull/85

**Comment by maxbachmann** [comment]
this is part of https://github.com/project-alice-powered-by-snips/ProjectAliceModules/pull/46 now so this will be closed

**Pull request closed without merging**
