### PR TITLE
german translation

### PR DESCRIPTION
**Pull request by maxbachmann**
I added some german translations

### CODE REVIEW

**Comment by Psychokiller1888** [comment]
Thank you! You are missing the dialogTemplate to generate the Snips assistant. And add youself in the install file as a maintainer ;)

**Comment by maxbachmann** [comment]
I will add both.
When checking skills created by snips they usually use around 200-300 training examples while you only use quite a few. Is this because it's pretty hard to find a lot of good examples or because there is not much improvement when adding more examples?

**Comment by Psychokiller1888** [comment]
Adding too many training exemples is of no use. Adding more is a good thing though, but time consuming. Alice will register wrong intents and allow user to train her live and keep a trace of what was wrong, where the users will be able to decide to share on the modules to improve them

**Comment by maxbachmann** [comment]
How can I add myself as a maintainer in the install file? I did not find any option to add multiple maintainers

**Comment by Psychokiller1888** [comment]
Oh yeah, lol, these are old installers still, did not commit yesterday. No prob, i'll add you!

**Pull request merged**
